version: "3"

services:
  reverse-proxy:
    image: nginx:1.17.6
    container_name: nginx_docker
    volumes:
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./etc/ssl:/etc/ssl"                                                  
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - web

  web:
    image: myapache
    container_name: web_docker
    expose:
      - "80"
    volumes:
      - "./web:/var/www/html"
      - "./web/log:/var/log/httpd"
      - "./etc/httpd/conf/httpd.conf:/etc/httpd/conf/httpd.conf"
      - "./etc/httpd/conf.d/httpd-vhosts.conf:/etc/httpd/conf.d/httpd-vhosts.conf"
    command: /bin/sh -c "/usr/sbin/php-fpm -D && /usr/sbin/httpd -DFOREGROUND"
    restart: always
